using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Net.Mail;
using System.Net;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Net;
using System.Net.Mail;

namespace EnviadorEmails
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        // nombre_apellidos ; email ; fichero.pdf
        private void button1_Click(object sender, EventArgs e)
        {

            SmtpClient client = new SmtpClient("smtp.gmail.com", 587);
            client.UseDefaultCredentials = false;
            // PASSWORD GENERATED BY https://myaccount.google.com/apppasswords
            client.Credentials = new NetworkCredential("drakusjordi74@gmail.com", "ixakwtvwntpgpqro");
            client.EnableSsl = true;

            MailMessage mailMessage = new MailMessage();
            mailMessage.From = new MailAddress("youremail@gmail.com");
            mailMessage.To.Add("jordiserrano@protonmail.ch");
            mailMessage.Subject = "Subject: Heyy";
            mailMessage.Body = "Body: heyyy!";

            //mailMessage.DeliveryNotificationOptions = System.Net.Mail.DeliveryNotificationOptions.OnSuccess;
            //mailMessage.Headers.Add("Disposition-Notification-To", "<ozenisek@centrum.cz>");
            //mailMessage.Headers.Add("Return-Receipt-To", "<o.zenisek@regnum-software.com>");


            string filepath = "";


            OpenFileDialog openFileDialog1 = new OpenFileDialog();

            openFileDialog1.InitialDirectory = "c:\\";
            //openFileDialog1.Filter = "Database files (*.mdb, *.accdb)|*.mdb;*.accdb";
            openFileDialog1.FilterIndex = 0;
            openFileDialog1.RestoreDirectory = true;

            if (openFileDialog1.ShowDialog() == DialogResult.OK)
            {
                string selectedFileName = openFileDialog1.FileName;
                Attachment atachment = new Attachment(selectedFileName);
                mailMessage.Attachments.Add(atachment);
                client.Send(mailMessage);

            }

            /*
             using(var reader = new StreamReader(@"C:\test.csv"))
                {
                    List<string> listA = new List<string>();
                    List<string> listB = new List<string>();
                    while (!reader.EndOfStream)
                    {
                        var line = reader.ReadLine();
                        var values = line.Split(';');

                        listA.Add(values[0]);
                        listB.Add(values[1]);
                    }
                }
             */


        }
    }
}
